version: '3'

services:
  frontend:
    build:
      context: ./Frontend
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19000:19000'
    volumes:
      - ./Frontend/Agit:/opt/Agit/app:delegated
      - ./Frontend/Agit/package.json:/opt/Agit/package.json
      - ./Frontend/Agit/package-lock.json:/opt/Agit/package-lock.json
    healthcheck:
      disable: true
