version: '3'

services:
  frontend:
    build:
      context: ./Frontend
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19000:19000'
    volumes:
      - ./Frontend/Agit:/opt/Agit/app:delegated
      - ./Frontend/Agit/package.json:/opt/Agit/package.json
      - ./Frontend/Agit/package-lock.json:/opt/Agit/package-lock.json
    healthcheck:
      disable: true

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - express-mysql-network

  adminer:
    image: adminer
    container_name: adminer-docker
    depends_on:
      - mysql-docker
    ports:
      - '8080:8080'
    networks:
      - express-mysql-network
    restart: on-failure

volumes:
  my-db:

networks:
  express-mysql-network: